---
driver:
  name: vagrant
  network:
  - ["private_network", { ip: "10.250.0.2" }]
  - ["forwarded_port", {guest: 8000, host: 80}]

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4
    driver_config:
      customize:
        memory: 4096

suites:
  - name: default
    run_list: role[operations]
    attributes:
