source 'https://rubygems.org'

gem 'berkshelf'
gem 'strainer', '~> 3.3.0'
gem 'chef', '~> 11.10.0'
gem 'rubocop', '~> 0.18.1'
gem 'foodcritic', '~> 3.0.0'
gem 'chefspec', '~> 3.2.0'
gem 'serverspec', '~> 0.15.2'
gem 'test-kitchen'
gem 'kitchen-vagrant'
gem 'chef-zero'
